name: Build and Release SmartTaskManager

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Compile Java files
      run: |
        mkdir -p out
        javac -d out src/com/taskmanager/*.java src/com/taskmanager/model/*.java src/com/taskmanager/model/enums/*.java src/com/taskmanager/service/*.java
    
    - name: Create JAR file
      run: |
        jar cfe SmartTaskManager.jar com.taskmanager.Main -C out .
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: SmartTaskManager.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}